// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/contract": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new contract entity using the provided data in the request body.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contract"
                ],
                "summary": "Create a new contract",
                "parameters": [
                    {
                        "description": "contract information",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.CreateContractRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.CreateContractReply"
                        }
                    }
                }
            }
        },
        "/api/v1/contract/deploy": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "将完整的借贷合约套件部署到指定的区块链网络。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contract"
                ],
                "summary": "部署所有合约",
                "parameters": [
                    {
                        "description": "部署参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.DeployRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.DeployReply"
                        }
                    }
                }
            }
        },
        "/api/v1/contract/list": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a paginated list of contract based on query filters, including page number and size.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contract"
                ],
                "summary": "Get a paginated list of contracts by custom conditions",
                "parameters": [
                    {
                        "description": "query parameters",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Params"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ListContractsReply"
                        }
                    }
                }
            }
        },
        "/api/v1/contract/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Gets detailed information of a contract specified by the given id in the path.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contract"
                ],
                "summary": "Get a contract by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.GetContractByIDReply"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates the specified contract by given id in the path, support partial update.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contract"
                ],
                "summary": "Update a contract by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "contract information",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.UpdateContractByIDRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.UpdateContractByIDReply"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a existing contract identified by the given id in the path.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contract"
                ],
                "summary": "Delete a contract by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.DeleteContractByIDReply"
                        }
                    }
                }
            }
        },
        "/api/v1/login": {
            "post": {
                "description": "Authenticates user and returns a JWT token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "login credentials",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.LoginReply"
                        }
                    }
                }
            }
        },
        "/api/v1/poolbases": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new poolbases entity using the provided data in the request body.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "poolbases"
                ],
                "summary": "Create a new poolbases",
                "parameters": [
                    {
                        "description": "poolbases information",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.CreatePoolbasesRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.CreatePoolbasesReply"
                        }
                    }
                }
            }
        },
        "/api/v1/poolbases/list": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a paginated list of poolbases based on query filters, including page number and size.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "poolbases"
                ],
                "summary": "Get a paginated list of poolbasess by custom conditions",
                "parameters": [
                    {
                        "description": "query parameters",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Params"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ListPoolbasessReply"
                        }
                    }
                }
            }
        },
        "/api/v1/poolbases/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Gets detailed information of a poolbases specified by the given id in the path.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "poolbases"
                ],
                "summary": "Get a poolbases by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.GetPoolbasesByIDReply"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates the specified poolbases by given id in the path, support partial update.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "poolbases"
                ],
                "summary": "Update a poolbases by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "poolbases information",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.UpdatePoolbasesByIDRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.UpdatePoolbasesByIDReply"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a existing poolbases identified by the given id in the path.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "poolbases"
                ],
                "summary": "Delete a poolbases by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.DeletePoolbasesByIDReply"
                        }
                    }
                }
            }
        },
        "/api/v1/pooldata": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new pooldata entity using the provided data in the request body.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pooldata"
                ],
                "summary": "Create a new pooldata",
                "parameters": [
                    {
                        "description": "pooldata information",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.CreatePooldataRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.CreatePooldataReply"
                        }
                    }
                }
            }
        },
        "/api/v1/pooldata/list": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a paginated list of pooldata based on query filters, including page number and size.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pooldata"
                ],
                "summary": "Get a paginated list of pooldatas by custom conditions",
                "parameters": [
                    {
                        "description": "query parameters",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Params"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ListPooldatasReply"
                        }
                    }
                }
            }
        },
        "/api/v1/pooldata/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Gets detailed information of a pooldata specified by the given id in the path.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pooldata"
                ],
                "summary": "Get a pooldata by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.GetPooldataByIDReply"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates the specified pooldata by given id in the path, support partial update.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pooldata"
                ],
                "summary": "Update a pooldata by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "pooldata information",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.UpdatePooldataByIDRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.UpdatePooldataByIDReply"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a existing pooldata identified by the given id in the path.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pooldata"
                ],
                "summary": "Delete a pooldata by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.DeletePooldataByIDReply"
                        }
                    }
                }
            }
        },
        "/api/v1/register": {
            "post": {
                "description": "Registers a new user with validation rules.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "User register",
                "parameters": [
                    {
                        "description": "registration info",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.RegisterReply"
                        }
                    }
                }
            }
        },
        "/api/v1/tokenInfo": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new tokenInfo entity using the provided data in the request body.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tokenInfo"
                ],
                "summary": "Create a new tokenInfo",
                "parameters": [
                    {
                        "description": "tokenInfo information",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.CreateTokenInfoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.CreateTokenInfoReply"
                        }
                    }
                }
            }
        },
        "/api/v1/tokenInfo/list": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a paginated list of tokenInfo based on query filters, including page number and size.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tokenInfo"
                ],
                "summary": "Get a paginated list of tokenInfos by custom conditions",
                "parameters": [
                    {
                        "description": "query parameters",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Params"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ListTokenInfosReply"
                        }
                    }
                }
            }
        },
        "/api/v1/tokenInfo/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Gets detailed information of a tokenInfo specified by the given id in the path.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tokenInfo"
                ],
                "summary": "Get a tokenInfo by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.GetTokenInfoByIDReply"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates the specified tokenInfo by given id in the path, support partial update.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tokenInfo"
                ],
                "summary": "Update a tokenInfo by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "tokenInfo information",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.UpdateTokenInfoByIDRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.UpdateTokenInfoByIDReply"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a existing tokenInfo identified by the given id in the path.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tokenInfo"
                ],
                "summary": "Delete a tokenInfo by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.DeleteTokenInfoByIDReply"
                        }
                    }
                }
            }
        },
        "/api/v1/user": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new user entity using the provided data in the request body.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Create a new user",
                "parameters": [
                    {
                        "description": "user information",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.CreateUserReply"
                        }
                    }
                }
            }
        },
        "/api/v1/user/list": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a paginated list of user based on query filters, including page number and size.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Get a paginated list of users by custom conditions",
                "parameters": [
                    {
                        "description": "query parameters",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Params"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ListUsersReply"
                        }
                    }
                }
            }
        },
        "/api/v1/user/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Gets detailed information of a user specified by the given id in the path.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Get a user by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.GetUserByIDReply"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates the specified user by given id in the path, support partial update.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Update a user by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "user information",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.UpdateUserByIDRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.UpdateUserByIDReply"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a existing user identified by the given id in the path.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Delete a user by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.DeleteUserByIDReply"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "types.Column": {
            "type": "object",
            "properties": {
                "exp": {
                    "description": "expressions, which default to = when the value is null, have =, !=, \u003e, \u003e=, \u003c, \u003c=, like",
                    "type": "string"
                },
                "logic": {
                    "description": "logical type, default value is \"and\", support \u0026, and, ||, or",
                    "type": "string"
                },
                "name": {
                    "description": "column name",
                    "type": "string"
                },
                "value": {
                    "description": "column value"
                }
            }
        },
        "types.ContractObjDetail": {
            "type": "object",
            "properties": {
                "chainID": {
                    "description": "链 ID: 56=BSC 主网 97=BSC 测试网",
                    "type": "string"
                },
                "contractAddress": {
                    "description": "合约地址",
                    "type": "string"
                },
                "contractName": {
                    "description": "合约名称",
                    "type": "string"
                },
                "createdAt": {
                    "description": "创建时间",
                    "type": "string"
                },
                "id": {
                    "description": "convert to uint64 id",
                    "type": "integer"
                },
                "nodeURL": {
                    "description": "主键ID",
                    "type": "string"
                },
                "publisherAddress": {
                    "description": "合约发布者地址",
                    "type": "string"
                },
                "txHash": {
                    "description": "部署交易哈希",
                    "type": "string"
                },
                "updatedAt": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        },
        "types.CreateContractReply": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "return code",
                    "type": "integer"
                },
                "data": {
                    "description": "return data",
                    "type": "object",
                    "properties": {
                        "id": {
                            "description": "id",
                            "type": "integer"
                        }
                    }
                },
                "msg": {
                    "description": "return information description",
                    "type": "string"
                }
            }
        },
        "types.CreateContractRequest": {
            "type": "object",
            "properties": {
                "chainID": {
                    "description": "链 ID: 56=BSC 主网 97=BSC 测试网",
                    "type": "string"
                },
                "contractAddress": {
                    "description": "合约地址",
                    "type": "string"
                },
                "contractName": {
                    "description": "合约名称",
                    "type": "string"
                },
                "nodeURL": {
                    "description": "合约发布网站地址，如127.0.0.1:8454",
                    "type": "string"
                },
                "publisherAddress": {
                    "description": "合约发布者地址",
                    "type": "string"
                },
                "txHash": {
                    "description": "部署交易哈希",
                    "type": "string"
                }
            }
        },
        "types.CreatePoolbasesReply": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "return code",
                    "type": "integer"
                },
                "data": {
                    "description": "return data",
                    "type": "object",
                    "properties": {
                        "id": {
                            "description": "id",
                            "type": "integer"
                        }
                    }
                },
                "msg": {
                    "description": "return information description",
                    "type": "string"
                }
            }
        },
        "types.CreatePoolbasesRequest": {
            "type": "object",
            "properties": {
                "autoLiquidateThreshold": {
                    "description": "自动清算阈值(精度值)",
                    "type": "string"
                },
                "borrowDebtToken": {
                    "description": "借入(抵押)侧池子代币/合约地址(质押资产)",
                    "type": "string"
                },
                "borrowSupply": {
                    "description": "当前已借入(抵押)总量",
                    "type": "string"
                },
                "borrowToken": {
                    "description": "借入(抵押)资产合约地址(用户抵押的币)",
                    "type": "string"
                },
                "borrowTokenInfo": {
                    "description": "借入(抵押)代币信息: tokenName, tokenLogo, tokenPrice, borrowFee 等",
                    "type": "string"
                },
                "borrowTokenSymbol": {
                    "description": "借入(抵押)代币符号，如 BTC",
                    "type": "string"
                },
                "chainID": {
                    "description": "链 ID: 56=BSC 主网 97=BSC 测试网",
                    "type": "string"
                },
                "endTime": {
                    "description": "池子结束时间戳",
                    "type": "string"
                },
                "interestRate": {
                    "description": "利率(精度值，如 10000000 表示 1%)",
                    "type": "string"
                },
                "lendDebtToken": {
                    "description": "出借侧池子代币/合约地址(出借凭证)",
                    "type": "string"
                },
                "lendSupply": {
                    "description": "当前已出借总量",
                    "type": "string"
                },
                "lendToken": {
                    "description": "出借资产合约地址(用户借出的币)",
                    "type": "string"
                },
                "lendTokenInfo": {
                    "description": "出借代币信息: tokenName, tokenLogo, tokenPrice, lendFee 等",
                    "type": "string"
                },
                "lendTokenSymbol": {
                    "description": "出借代币符号，如 BUSD",
                    "type": "string"
                },
                "maxSupply": {
                    "description": "池子最大可借/可存额度(最小单位)",
                    "type": "string"
                },
                "mortgageRate": {
                    "description": "抵押率(精度值，如 10000000=100%)",
                    "type": "string"
                },
                "poolID": {
                    "description": "业务池子 ID，与链上 pool 对应",
                    "type": "integer"
                },
                "settleTime": {
                    "description": "结算开始时间戳",
                    "type": "string"
                },
                "state": {
                    "description": "池子状态: 0未开启 1进行中 2已结算 3清算中 4未开启等",
                    "type": "string"
                }
            }
        },
        "types.CreatePooldataReply": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "return code",
                    "type": "integer"
                },
                "data": {
                    "description": "return data",
                    "type": "object",
                    "properties": {
                        "id": {
                            "description": "id",
                            "type": "integer"
                        }
                    }
                },
                "msg": {
                    "description": "return information description",
                    "type": "string"
                }
            }
        },
        "types.CreatePooldataRequest": {
            "type": "object",
            "properties": {
                "chainID": {
                    "description": "链 ID，与 poolbases 一致",
                    "type": "string"
                },
                "finishAmountBorrow": {
                    "description": "已完成/归还的借入侧金额",
                    "type": "string"
                },
                "finishAmountLend": {
                    "description": "已完成/归还的借出侧金额",
                    "type": "string"
                },
                "liquidationAmounBorrow": {
                    "description": "清算产生的借入侧金额",
                    "type": "string"
                },
                "liquidationAmounLend": {
                    "description": "清算产生的借出侧金额",
                    "type": "string"
                },
                "poolID": {
                    "description": "池子 ID，与 poolbases.pool_id 对应",
                    "type": "string"
                },
                "settleAmountBorrow": {
                    "description": "结算时借入侧(抵押)金额",
                    "type": "string"
                },
                "settleAmountLend": {
                    "description": "结算时借出侧(贷方)金额",
                    "type": "string"
                }
            }
        },
        "types.CreateTokenInfoReply": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "return code",
                    "type": "integer"
                },
                "data": {
                    "description": "return data",
                    "type": "object",
                    "properties": {
                        "id": {
                            "description": "id",
                            "type": "integer"
                        }
                    }
                },
                "msg": {
                    "description": "return information description",
                    "type": "string"
                }
            }
        },
        "types.CreateTokenInfoRequest": {
            "type": "object",
            "properties": {
                "chainID": {
                    "description": "链 ID: 56=BSC 97=测试网",
                    "type": "string"
                },
                "decimals": {
                    "description": "代币精度(小数位数)",
                    "type": "integer"
                },
                "logo": {
                    "description": "代币 logo URL",
                    "type": "string"
                },
                "price": {
                    "description": "价格(精度值，用于估值与清算)",
                    "type": "string"
                },
                "symbol": {
                    "description": "代币符号，如 BUSD/BTC",
                    "type": "string"
                },
                "token": {
                    "description": "代币合约地址",
                    "type": "string"
                }
            }
        },
        "types.CreateUserReply": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "return code",
                    "type": "integer"
                },
                "data": {
                    "description": "return data",
                    "type": "object",
                    "properties": {
                        "id": {
                            "description": "id",
                            "type": "integer"
                        }
                    }
                },
                "msg": {
                    "description": "return information description",
                    "type": "string"
                }
            }
        },
        "types.CreateUserRequest": {
            "type": "object",
            "properties": {
                "login": {
                    "description": "用户账号",
                    "type": "string"
                },
                "nike": {
                    "description": "用户昵称",
                    "type": "string"
                },
                "password": {
                    "description": "加密后的密码",
                    "type": "string"
                }
            }
        },
        "types.DeleteContractByIDReply": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "return code",
                    "type": "integer"
                },
                "data": {
                    "description": "return data",
                    "type": "object"
                },
                "msg": {
                    "description": "return information description",
                    "type": "string"
                }
            }
        },
        "types.DeletePoolbasesByIDReply": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "return code",
                    "type": "integer"
                },
                "data": {
                    "description": "return data",
                    "type": "object"
                },
                "msg": {
                    "description": "return information description",
                    "type": "string"
                }
            }
        },
        "types.DeletePooldataByIDReply": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "return code",
                    "type": "integer"
                },
                "data": {
                    "description": "return data",
                    "type": "object"
                },
                "msg": {
                    "description": "return information description",
                    "type": "string"
                }
            }
        },
        "types.DeleteTokenInfoByIDReply": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "return code",
                    "type": "integer"
                },
                "data": {
                    "description": "return data",
                    "type": "object"
                },
                "msg": {
                    "description": "return information description",
                    "type": "string"
                }
            }
        },
        "types.DeleteUserByIDReply": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "return code",
                    "type": "integer"
                },
                "data": {
                    "description": "return data",
                    "type": "object"
                },
                "msg": {
                    "description": "return information description",
                    "type": "string"
                }
            }
        },
        "types.DeployContractItem": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "txHash": {
                    "type": "string"
                }
            }
        },
        "types.DeployData": {
            "type": "object",
            "properties": {
                "chainName": {
                    "type": "string"
                },
                "contracts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.DeployContractItem"
                    }
                },
                "deployer": {
                    "type": "string"
                },
                "pledgePoolAddr": {
                    "type": "string"
                },
                "rpcUrl": {
                    "type": "string"
                }
            }
        },
        "types.DeployReply": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/types.DeployData"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "types.DeployRequest": {
            "type": "object",
            "required": [
                "privateKey",
                "rpcUrl"
            ],
            "properties": {
                "borrowTokenName": {
                    "description": "MockBorrowToken 名称",
                    "type": "string"
                },
                "borrowTokenSym": {
                    "description": "MockBorrowToken 符号",
                    "type": "string"
                },
                "chainName": {
                    "description": "链名称（如 hardhat）",
                    "type": "string"
                },
                "debtTokenName": {
                    "description": "债务代币名称",
                    "type": "string"
                },
                "debtTokenSym": {
                    "description": "债务代币符号",
                    "type": "string"
                },
                "factoryFeeTo": {
                    "description": "Factory feeToSetter（默认部署者地址）",
                    "type": "string"
                },
                "feeAddress": {
                    "description": "手续费接收地址（默认部署者地址）",
                    "type": "string"
                },
                "lendTokenName": {
                    "description": "MockLendToken 名称",
                    "type": "string"
                },
                "lendTokenSym": {
                    "description": "MockLendToken 符号",
                    "type": "string"
                },
                "oracleOwner": {
                    "description": "BscPledgeOracle owner（默认部署者地址）",
                    "type": "string"
                },
                "poolOwner": {
                    "description": "PledgePool owner（默认部署者地址）",
                    "type": "string"
                },
                "privateKey": {
                    "description": "部署者私钥（必填）",
                    "type": "string"
                },
                "rpcUrl": {
                    "description": "RPC URL（必填）",
                    "type": "string"
                },
                "tokenSupply": {
                    "description": "MockToken 初始发行量",
                    "type": "string"
                }
            }
        },
        "types.GetContractByIDReply": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "return code",
                    "type": "integer"
                },
                "data": {
                    "description": "return data",
                    "type": "object",
                    "properties": {
                        "contract": {
                            "$ref": "#/definitions/types.ContractObjDetail"
                        }
                    }
                },
                "msg": {
                    "description": "return information description",
                    "type": "string"
                }
            }
        },
        "types.GetPoolbasesByIDReply": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "return code",
                    "type": "integer"
                },
                "data": {
                    "description": "return data",
                    "type": "object",
                    "properties": {
                        "poolbases": {
                            "$ref": "#/definitions/types.PoolbasesObjDetail"
                        }
                    }
                },
                "msg": {
                    "description": "return information description",
                    "type": "string"
                }
            }
        },
        "types.GetPooldataByIDReply": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "return code",
                    "type": "integer"
                },
                "data": {
                    "description": "return data",
                    "type": "object",
                    "properties": {
                        "pooldata": {
                            "$ref": "#/definitions/types.PooldataObjDetail"
                        }
                    }
                },
                "msg": {
                    "description": "return information description",
                    "type": "string"
                }
            }
        },
        "types.GetTokenInfoByIDReply": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "return code",
                    "type": "integer"
                },
                "data": {
                    "description": "return data",
                    "type": "object",
                    "properties": {
                        "tokenInfo": {
                            "$ref": "#/definitions/types.TokenInfoObjDetail"
                        }
                    }
                },
                "msg": {
                    "description": "return information description",
                    "type": "string"
                }
            }
        },
        "types.GetUserByIDReply": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "return code",
                    "type": "integer"
                },
                "data": {
                    "description": "return data",
                    "type": "object",
                    "properties": {
                        "user": {
                            "$ref": "#/definitions/types.UserObjDetail"
                        }
                    }
                },
                "msg": {
                    "description": "return information description",
                    "type": "string"
                }
            }
        },
        "types.ListContractsReply": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "return code",
                    "type": "integer"
                },
                "data": {
                    "description": "return data",
                    "type": "object",
                    "properties": {
                        "contracts": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.ContractObjDetail"
                            }
                        }
                    }
                },
                "msg": {
                    "description": "return information description",
                    "type": "string"
                }
            }
        },
        "types.ListPoolbasessReply": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "return code",
                    "type": "integer"
                },
                "data": {
                    "description": "return data",
                    "type": "object",
                    "properties": {
                        "poolbasess": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.PoolbasesObjDetail"
                            }
                        }
                    }
                },
                "msg": {
                    "description": "return information description",
                    "type": "string"
                }
            }
        },
        "types.ListPooldatasReply": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "return code",
                    "type": "integer"
                },
                "data": {
                    "description": "return data",
                    "type": "object",
                    "properties": {
                        "pooldatas": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.PooldataObjDetail"
                            }
                        }
                    }
                },
                "msg": {
                    "description": "return information description",
                    "type": "string"
                }
            }
        },
        "types.ListTokenInfosReply": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "return code",
                    "type": "integer"
                },
                "data": {
                    "description": "return data",
                    "type": "object",
                    "properties": {
                        "tokenInfos": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.TokenInfoObjDetail"
                            }
                        }
                    }
                },
                "msg": {
                    "description": "return information description",
                    "type": "string"
                }
            }
        },
        "types.ListUsersReply": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "return code",
                    "type": "integer"
                },
                "data": {
                    "description": "return data",
                    "type": "object",
                    "properties": {
                        "users": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.UserObjDetail"
                            }
                        }
                    }
                },
                "msg": {
                    "description": "return information description",
                    "type": "string"
                }
            }
        },
        "types.LoginReply": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "return code",
                    "type": "integer"
                },
                "data": {
                    "description": "return data",
                    "type": "object",
                    "properties": {
                        "token": {
                            "description": "jwt token",
                            "type": "string"
                        }
                    }
                },
                "msg": {
                    "description": "return information description",
                    "type": "string"
                }
            }
        },
        "types.LoginRequest": {
            "type": "object",
            "required": [
                "login",
                "password"
            ],
            "properties": {
                "login": {
                    "description": "用户账号",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                }
            }
        },
        "types.Params": {
            "type": "object",
            "properties": {
                "columns": {
                    "description": "query conditions",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Column"
                    }
                },
                "limit": {
                    "description": "lines per page",
                    "type": "integer"
                },
                "page": {
                    "description": "page number, starting from page 0",
                    "type": "integer"
                },
                "sort": {
                    "description": "sorted fields, multi-column sorting separated by commas",
                    "type": "string"
                }
            }
        },
        "types.PoolbasesObjDetail": {
            "type": "object",
            "properties": {
                "autoLiquidateThreshold": {
                    "description": "自动清算阈值(精度值)",
                    "type": "string"
                },
                "borrowDebtToken": {
                    "description": "借入(抵押)侧池子代币/合约地址(质押资产)",
                    "type": "string"
                },
                "borrowSupply": {
                    "description": "当前已借入(抵押)总量",
                    "type": "string"
                },
                "borrowToken": {
                    "description": "借入(抵押)资产合约地址(用户抵押的币)",
                    "type": "string"
                },
                "borrowTokenInfo": {
                    "description": "借入(抵押)代币信息: tokenName, tokenLogo, tokenPrice, borrowFee 等",
                    "type": "string"
                },
                "borrowTokenSymbol": {
                    "description": "借入(抵押)代币符号，如 BTC",
                    "type": "string"
                },
                "chainID": {
                    "description": "链 ID: 56=BSC 主网 97=BSC 测试网",
                    "type": "string"
                },
                "createdAt": {
                    "description": "创建时间",
                    "type": "string"
                },
                "endTime": {
                    "description": "池子结束时间戳",
                    "type": "string"
                },
                "id": {
                    "description": "convert to uint64 id",
                    "type": "integer"
                },
                "interestRate": {
                    "description": "利率(精度值，如 10000000 表示 1%)",
                    "type": "string"
                },
                "lendDebtToken": {
                    "description": "出借侧池子代币/合约地址(出借凭证)",
                    "type": "string"
                },
                "lendSupply": {
                    "description": "当前已出借总量",
                    "type": "string"
                },
                "lendToken": {
                    "description": "出借资产合约地址(用户借出的币)",
                    "type": "string"
                },
                "lendTokenInfo": {
                    "description": "出借代币信息: tokenName, tokenLogo, tokenPrice, lendFee 等",
                    "type": "string"
                },
                "lendTokenSymbol": {
                    "description": "出借代币符号，如 BUSD",
                    "type": "string"
                },
                "maxSupply": {
                    "description": "池子最大可借/可存额度(最小单位)",
                    "type": "string"
                },
                "mortgageRate": {
                    "description": "抵押率(精度值，如 10000000=100%)",
                    "type": "string"
                },
                "poolID": {
                    "description": "主键ID",
                    "type": "integer"
                },
                "settleTime": {
                    "description": "结算开始时间戳",
                    "type": "string"
                },
                "state": {
                    "description": "池子状态: 0未开启 1进行中 2已结算 3清算中 4未开启等",
                    "type": "string"
                },
                "updatedAt": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        },
        "types.PooldataObjDetail": {
            "type": "object",
            "properties": {
                "chainID": {
                    "description": "主键ID",
                    "type": "string"
                },
                "createdAt": {
                    "description": "创建时间",
                    "type": "string"
                },
                "finishAmountBorrow": {
                    "description": "已完成/归还的借入侧金额",
                    "type": "string"
                },
                "finishAmountLend": {
                    "description": "已完成/归还的借出侧金额",
                    "type": "string"
                },
                "id": {
                    "description": "convert to uint64 id",
                    "type": "integer"
                },
                "liquidationAmounBorrow": {
                    "description": "清算产生的借入侧金额",
                    "type": "string"
                },
                "liquidationAmounLend": {
                    "description": "清算产生的借出侧金额",
                    "type": "string"
                },
                "poolID": {
                    "description": "池子 ID，与 poolbases.pool_id 对应",
                    "type": "string"
                },
                "settleAmountBorrow": {
                    "description": "结算时借入侧(抵押)金额",
                    "type": "string"
                },
                "settleAmountLend": {
                    "description": "结算时借出侧(贷方)金额",
                    "type": "string"
                },
                "updatedAt": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        },
        "types.RegisterReply": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "return code",
                    "type": "integer"
                },
                "data": {
                    "description": "return data",
                    "type": "object",
                    "properties": {
                        "id": {
                            "description": "用户ID",
                            "type": "integer"
                        }
                    }
                },
                "msg": {
                    "description": "return information description",
                    "type": "string"
                }
            }
        },
        "types.RegisterRequest": {
            "type": "object",
            "required": [
                "login",
                "nike",
                "password"
            ],
            "properties": {
                "login": {
                    "description": "用户账号 (3-10位字母或数字)",
                    "type": "string"
                },
                "nike": {
                    "description": "用户昵称 (1-12位)",
                    "type": "string"
                },
                "password": {
                    "description": "密码 (8-20位)",
                    "type": "string"
                }
            }
        },
        "types.TokenInfoObjDetail": {
            "type": "object",
            "properties": {
                "chainID": {
                    "description": "链 ID: 56=BSC 97=测试网",
                    "type": "string"
                },
                "createdAt": {
                    "description": "创建时间",
                    "type": "string"
                },
                "decimals": {
                    "description": "代币精度(小数位数)",
                    "type": "integer"
                },
                "id": {
                    "description": "convert to uint64 id",
                    "type": "integer"
                },
                "logo": {
                    "description": "代币 logo URL",
                    "type": "string"
                },
                "price": {
                    "description": "价格(精度值，用于估值与清算)",
                    "type": "string"
                },
                "symbol": {
                    "description": "主键ID",
                    "type": "string"
                },
                "token": {
                    "description": "代币合约地址",
                    "type": "string"
                },
                "updatedAt": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        },
        "types.UpdateContractByIDReply": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "return code",
                    "type": "integer"
                },
                "data": {
                    "description": "return data",
                    "type": "object"
                },
                "msg": {
                    "description": "return information description",
                    "type": "string"
                }
            }
        },
        "types.UpdateContractByIDRequest": {
            "type": "object",
            "properties": {
                "chainID": {
                    "description": "链 ID: 56=BSC 主网 97=BSC 测试网",
                    "type": "string"
                },
                "contractAddress": {
                    "description": "合约地址",
                    "type": "string"
                },
                "contractName": {
                    "description": "合约名称",
                    "type": "string"
                },
                "id": {
                    "description": "uint64 id",
                    "type": "integer"
                },
                "nodeURL": {
                    "description": "主键ID",
                    "type": "string"
                },
                "publisherAddress": {
                    "description": "合约发布者地址",
                    "type": "string"
                },
                "txHash": {
                    "description": "部署交易哈希",
                    "type": "string"
                }
            }
        },
        "types.UpdatePoolbasesByIDReply": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "return code",
                    "type": "integer"
                },
                "data": {
                    "description": "return data",
                    "type": "object"
                },
                "msg": {
                    "description": "return information description",
                    "type": "string"
                }
            }
        },
        "types.UpdatePoolbasesByIDRequest": {
            "type": "object",
            "properties": {
                "autoLiquidateThreshold": {
                    "description": "自动清算阈值(精度值)",
                    "type": "string"
                },
                "borrowDebtToken": {
                    "description": "借入(抵押)侧池子代币/合约地址(质押资产)",
                    "type": "string"
                },
                "borrowSupply": {
                    "description": "当前已借入(抵押)总量",
                    "type": "string"
                },
                "borrowToken": {
                    "description": "借入(抵押)资产合约地址(用户抵押的币)",
                    "type": "string"
                },
                "borrowTokenInfo": {
                    "description": "借入(抵押)代币信息: tokenName, tokenLogo, tokenPrice, borrowFee 等",
                    "type": "string"
                },
                "borrowTokenSymbol": {
                    "description": "借入(抵押)代币符号，如 BTC",
                    "type": "string"
                },
                "chainID": {
                    "description": "链 ID: 56=BSC 主网 97=BSC 测试网",
                    "type": "string"
                },
                "endTime": {
                    "description": "池子结束时间戳",
                    "type": "string"
                },
                "id": {
                    "description": "uint64 id",
                    "type": "integer"
                },
                "interestRate": {
                    "description": "利率(精度值，如 10000000 表示 1%)",
                    "type": "string"
                },
                "lendDebtToken": {
                    "description": "出借侧池子代币/合约地址(出借凭证)",
                    "type": "string"
                },
                "lendSupply": {
                    "description": "当前已出借总量",
                    "type": "string"
                },
                "lendToken": {
                    "description": "出借资产合约地址(用户借出的币)",
                    "type": "string"
                },
                "lendTokenInfo": {
                    "description": "出借代币信息: tokenName, tokenLogo, tokenPrice, lendFee 等",
                    "type": "string"
                },
                "lendTokenSymbol": {
                    "description": "出借代币符号，如 BUSD",
                    "type": "string"
                },
                "maxSupply": {
                    "description": "池子最大可借/可存额度(最小单位)",
                    "type": "string"
                },
                "mortgageRate": {
                    "description": "抵押率(精度值，如 10000000=100%)",
                    "type": "string"
                },
                "poolID": {
                    "description": "主键ID",
                    "type": "integer"
                },
                "settleTime": {
                    "description": "结算开始时间戳",
                    "type": "string"
                },
                "state": {
                    "description": "池子状态: 0未开启 1进行中 2已结算 3清算中 4未开启等",
                    "type": "string"
                }
            }
        },
        "types.UpdatePooldataByIDReply": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "return code",
                    "type": "integer"
                },
                "data": {
                    "description": "return data",
                    "type": "object"
                },
                "msg": {
                    "description": "return information description",
                    "type": "string"
                }
            }
        },
        "types.UpdatePooldataByIDRequest": {
            "type": "object",
            "properties": {
                "chainID": {
                    "description": "主键ID",
                    "type": "string"
                },
                "finishAmountBorrow": {
                    "description": "已完成/归还的借入侧金额",
                    "type": "string"
                },
                "finishAmountLend": {
                    "description": "已完成/归还的借出侧金额",
                    "type": "string"
                },
                "id": {
                    "description": "uint64 id",
                    "type": "integer"
                },
                "liquidationAmounBorrow": {
                    "description": "清算产生的借入侧金额",
                    "type": "string"
                },
                "liquidationAmounLend": {
                    "description": "清算产生的借出侧金额",
                    "type": "string"
                },
                "poolID": {
                    "description": "池子 ID，与 poolbases.pool_id 对应",
                    "type": "string"
                },
                "settleAmountBorrow": {
                    "description": "结算时借入侧(抵押)金额",
                    "type": "string"
                },
                "settleAmountLend": {
                    "description": "结算时借出侧(贷方)金额",
                    "type": "string"
                }
            }
        },
        "types.UpdateTokenInfoByIDReply": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "return code",
                    "type": "integer"
                },
                "data": {
                    "description": "return data",
                    "type": "object"
                },
                "msg": {
                    "description": "return information description",
                    "type": "string"
                }
            }
        },
        "types.UpdateTokenInfoByIDRequest": {
            "type": "object",
            "properties": {
                "chainID": {
                    "description": "链 ID: 56=BSC 97=测试网",
                    "type": "string"
                },
                "decimals": {
                    "description": "代币精度(小数位数)",
                    "type": "integer"
                },
                "id": {
                    "description": "uint64 id",
                    "type": "integer"
                },
                "logo": {
                    "description": "代币 logo URL",
                    "type": "string"
                },
                "price": {
                    "description": "价格(精度值，用于估值与清算)",
                    "type": "string"
                },
                "symbol": {
                    "description": "主键ID",
                    "type": "string"
                },
                "token": {
                    "description": "代币合约地址",
                    "type": "string"
                }
            }
        },
        "types.UpdateUserByIDReply": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "return code",
                    "type": "integer"
                },
                "data": {
                    "description": "return data",
                    "type": "object"
                },
                "msg": {
                    "description": "return information description",
                    "type": "string"
                }
            }
        },
        "types.UpdateUserByIDRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "uint64 id",
                    "type": "integer"
                },
                "login": {
                    "description": "用户账号",
                    "type": "string"
                },
                "nike": {
                    "description": "用户昵称",
                    "type": "string"
                },
                "password": {
                    "description": "加密后的密码",
                    "type": "string"
                }
            }
        },
        "types.UserObjDetail": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "convert to uint64 id",
                    "type": "integer"
                },
                "login": {
                    "description": "用户账号",
                    "type": "string"
                },
                "nike": {
                    "description": "用户昵称",
                    "type": "string"
                },
                "password": {
                    "description": "加密后的密码",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type Bearer your-jwt-token to Value",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v1.0.0",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{"http", "https"},
	Title:            "pledge_be api docs",
	Description:      "http server api docs",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
